//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ultima5Redux.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ultima5Redux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Britannia&quot;: [
        ///    {
        ///      &quot;Index&quot;: 0,
        ///      &quot;Description&quot;: &quot;Camp Fire&quot;
        ///    },
        ///    {
        ///      &quot;Index&quot;: 1,
        ///      &quot;Description&quot;: &quot;Swamp&quot;
        ///    },
        ///    {
        ///      &quot;Index&quot;: 2,
        ///      &quot;Description&quot;: &quot;Glade&quot;
        ///    },
        ///    {
        ///      &quot;Index&quot;: 3,
        ///      &quot;Description&quot;: &quot;Treed&quot;
        ///    },
        ///    {
        ///      &quot;Index&quot;: 4,
        ///      &quot;Description&quot;: &quot;Desert&quot;
        ///    },
        ///    {
        ///      &quot;Index&quot;: 5,
        ///      &quot;Description&quot;: &quot;Clean Tree&quot;
        ///    },
        ///    {
        ///      &quot;Index&quot;: 6,
        ///      &quot;Description&quot;: &quot;Mountains&quot;
        ///    },
        ///    {
        ///      &quot;Index&quot;: 7,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CombatMaps {
            get {
                return ResourceManager.GetString("CombatMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;Reagent&quot;: [
        ///      {
        ///         &quot;ItemName&quot;: &quot;SulfurAsh&quot;,
        ///         &quot;ItemNameHighlight&quot;: &quot;sulphurous ash,ash&quot;,
        ///         &quot;ItemSprite&quot;: &quot;SulfurAsh.2d&quot;,
        ///         &quot;ItemSpriteExposed&quot;: 0,
        ///         &quot;ItemDescription&quot;: &quot;Common material left by volcanic action, ash is an excellent source of energy in magical mixtures.&quot;,
        ///         &quot;ItemDescriptionAttribution&quot;: &quot;The Book of Lore (Ultima V)&quot;
        ///      },
        ///      {
        ///         &quot;ItemName&quot;: &quot;Ginseng&quot;,
        ///         &quot;ItemNameHighlight&quot;: &quot;ginseng&quot;,
        ///         &quot;ItemSprite&quot;: &quot;Gi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InventoryDetails {
            get {
                return ResourceManager.GetString("InventoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;0&quot;: {
        ///    &quot;Location&quot;: &quot;Britain&quot;,
        ///    &quot;ShoppeKeeperType&quot;: &quot;Blacksmith&quot;
        ///  },
        ///  &quot;1&quot;: {
        ///    &quot;Location&quot;: &quot;Jhelom&quot;,
        ///    &quot;ShoppeKeeperType&quot;: &quot;Blacksmith&quot;
        ///  },
        ///  &quot;2&quot;: {
        ///    &quot;Location&quot;: &quot;Yew&quot;,
        ///    &quot;ShoppeKeeperType&quot;: &quot;Blacksmith&quot;
        ///  },
        ///  &quot;3&quot;: {
        ///    &quot;Location&quot;: &quot;Minoc&quot;,
        ///    &quot;ShoppeKeeperType&quot;: &quot;Blacksmith&quot;
        ///  },
        ///  &quot;4&quot;: {
        ///    &quot;Location&quot;: &quot;Trinsic&quot;,
        ///    &quot;ShoppeKeeperType&quot;: &quot;Blacksmith&quot;
        ///  },
        ///  &quot;5&quot;: {
        ///    &quot;Location&quot;: &quot;Lord_Britishs_Castle&quot;,
        ///    &quot;ShoppeKeeperType&quot;: &quot;Blacksmith&quot;
        ///  },
        ///  &quot;6&quot;: {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShoppeKeeperMap {
            get {
                return ResourceManager.GetString("ShoppeKeeperMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;0&quot;: {
        ///      &quot;Name&quot;: &quot;Explosion&quot;,
        ///      &quot;Description&quot;: &quot;&quot;,
        ///      &quot;IsWalking_Passable&quot;: true,
        ///      &quot;IsBoat_Passable&quot;: true,
        ///      &quot;IsSkiff_Passable&quot;: true,
        ///      &quot;IsCarpet_Passable&quot;: true,
        ///      &quot;IsHorse_Passable&quot;: true,
        ///      &quot;IsKlimable&quot;: false,
        ///      &quot;IsOpenable&quot;: false,
        ///      &quot;IsLandEnemyPassable&quot;: false,
        ///      &quot;IsWaterEnemyPassable&quot;: false,
        ///      &quot;SpeedFactor&quot;: 1,
        ///      &quot;IsPartOfAnimation&quot;: false,
        ///      &quot;AnimationIndex&quot;: 0,
        ///      &quot;IsUpright&quot;: true,
        ///      &quot;FlatTileSubstitutionIndex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TileData {
            get {
                return ResourceManager.GetString("TileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;0&quot;: [
        ///    {
        ///      &quot;X&quot;: 45,
        ///      &quot;Y&quot;: 62,
        ///      &quot;Z&quot;: 0,
        ///      &quot;SpriteNum&quot;: 5,
        ///      &quot;SpriteName&quot;: &quot;Grass&quot;,
        ///      &quot;Comment&quot;: &quot;Iolos hut&quot;
        ///    }
        ///  ],
        ///  &quot;2&quot;: [
        ///    {
        ///      &quot;X&quot;: 13,
        ///      &quot;Y&quot;: 19,
        ///      &quot;Z&quot;: 0,
        ///      &quot;SpriteNum&quot;: 48,
        ///      &quot;SpriteName&quot;: &quot;OutsidePath1&quot;,
        ///      &quot;Comment&quot;: &quot;Britain lamps&quot;
        ///    },
        ///    {
        ///      &quot;X&quot;: 17,
        ///      &quot;Y&quot;: 19,
        ///      &quot;Z&quot;: 0,
        ///      &quot;SpriteNum&quot;: 48,
        ///      &quot;SpriteName&quot;: &quot;OutsidePath1&quot;,
        ///      &quot;Comment&quot;: &quot;Britain lamps&quot;
        ///    },
        ///    {
        ///      &quot;X&quot;: 17,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TileOverrides {
            get {
                return ResourceManager.GetString("TileOverrides", resourceCulture);
            }
        }
    }
}
